### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by Kagami** [PistonDevelopers/resize#18]
https://travis-ci.org/PistonDevelopers/resize/jobs/218549902#L221

@bvssvni do you know why my doc deploy key isn't listed at https://github.com/PistonDevelopers/docs/settings/keys? I think I added it ~year ago but now it's now there…

**Comment by bvssvni** [comment]
@Kagami No, I don't know why it is isn't listed.

**Comment by Kagami** [comment]
Added, updated.
