### ISSUE TITLE
Filter in linear space

### ISSUE THREAD

**Issue by koalefant** [PistonDevelopers/resize#26]
Documentation recommends to "downscale in linear colorspace", what is expected way of doing this with this crate? 
Manually convert to RGB48/64 and back?

**Comment by kornelski** [comment]
Converting back and forth works.

`PixelFormat` is a trait. You could define your own, and convert to linear on the fly with:

https://docs.rs/resize/0.4.0/resize/trait.PixelFormat.html#tymethod.into_subpixel

**Comment by koalefant** [comment]
Thank you, this answers my question.
