### ISSUE TITLE
Performance issue with the redundancy operations

### ISSUE THREAD

**Issue by yyzdtccjdtc** [PistonDevelopers/resize#31]
https://github.com/PistonDevelopers/resize/blob/210614525704da62209fd2b85e08e3ff2a8056a9/src/px.rs#L185
https://github.com/PistonDevelopers/resize/blob/210614525704da62209fd2b85e08e3ff2a8056a9/src/px.rs#L199

For these two lines of code here, the round() function will introduce some redundancy memory operations with the call and ret instructions. Also, this round() function does some unnecessary checks, such as checking whether the input number is a negative number, which can also affect the runtime speed.

If we change the code to this, we can eliminate these redundant operations.

```
        #[inline(always)]
        fn from_float(f: f32) -> Self {
            (f + 0.5) as u8
        }
       
        ...

        #[inline(always)]
        fn from_float(f: f32) -> Self {
            (f + 0.5) as u16
        }
```
The value of f32 is automatically set to 0 or 255 when it is converted to u8 or u16 type, if it is less than 0 or greater than 255.

According to my tests with the resize example with this y4m application (https://github.com/yyzdtccjdtc/y4m), the average execution time decreased from 6.1s to 5s, which is a 1.22x speedup.

Hope this information helps!

**Comment by kornelski** [comment]
Thanks for the tip. I don't see speed difference on M1 ARM, but it does avoid a call to roundf().
